config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  resources :shops do
    resources :tickets
    resources :census
  end

  #resources :census
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/models/censu.rb
class Censu < ApplicationRecord
  belongs_to :shop
end

app/controllers/census_controller.rb
class CensusController < ApplicationController
  before_action :set_censu, only: [:show, :edit, :update, :destroy]

  # GET /census
  # GET /census.json
  def index
    @census = Censu.all
  end

  # GET /census/1
  # GET /census/1.json
  def show
  end

  # GET /census/new
  def new
    @shop = Shop.find(params[:shop_id])
    @censu = @shop.census.new
  end

  # GET /census/1/edit
  def edit
  end

  # POST /census
  # POST /census.json
  def create
    @shop = Shop.find(params[:shop_id])
    @censu = @shop.census.new(censu_params.except(:return))

    respond_to do |format|
      if @censu.save
        format.html { redirect_to shop_ticket_path(@shop, censu_params[:return]), notice: 'Danke für die Mithilfe!' }
        format.json { render :show, status: :created, location: @censu }
      else
        format.html { render :new }
        format.json { render json: @censu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /census/1
  # PATCH/PUT /census/1.json
  def update
    respond_to do |format|
      if @censu.update(censu_params)
        format.html { redirect_to @censu, notice: 'Censu was successfully updated.' }
        format.json { render :show, status: :ok, location: @censu }
      else
        format.html { render :edit }
        format.json { render json: @censu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /census/1
  # DELETE /census/1.json
  def destroy
    @censu.destroy
    respond_to do |format|
      format.html { redirect_to census_url, notice: 'Censu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_censu
      @censu = Censu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def censu_params
      params.require(:censu).permit(:sum, :shop_id, :return)
    end
end

app/helpers/census_helper.rb
module CensusHelper
end

app/views/census/_form.html.haml
= form_with(model: censu, url: [@shop, @census] local: true) do |form|
  - if censu.errors.any?
    #error_explanation
      %h2
        = pluralize(censu.errors.count, "error")
        prohibited this censu from being saved:
      %ul
        - censu.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :sum
    = form.number_field :sum
  .field
    = form.label :shop_id
    = form.text_field :shop_id
  .actions
    = form.submit

app/views/census/edit.html.haml
= render 'form', censu: @censu

app/views/census/index.html.haml
%p#notice= notice
%h1 Census
%table
  %thead
    %tr
      %th Sum
      %th Shop
      %th{:colspan => "3"}
  %tbody
    - @census.each do |censu|
      %tr
        %td= censu.sum
        %td= censu.shop_id
        %td= link_to 'Show', censu
        %td= link_to 'Edit', edit_censu_path(censu)
        %td= link_to 'Destroy', censu, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Censu', new_censu_path

app/views/census/new.html.haml
= render 'form', censu: @censu

app/views/census/show.html.haml
%p
  %strong Sum:
  = @censu.sum
%p
  %strong Shop:
  = @censu.shop_id