config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  resources :shops do
    resources :tickets
    resources :census
  end

  #resources :census
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/models/shop.rb
class Shop < ApplicationRecord

    has_many :census
    has_many :tickets

    def state
        if census.exists?
            case census.last.sum
            when 0..10 then "empty"
            when 11..50 then "busy"
            else
                "full"
            end
        else
            "no_data"
        end
    end

    def status
        if census.exists?
            case census.last.sum
            when 0..10 then "green"
            when 11..50 then "yellow"
            else
                "red"
            end
        else
            "blue"
        end
    end

    def pax
        if self.census.any?
            self.census.last.sum
        end
    end

    def address
        unless self.street.nil? || self.housenumber.nil?
            self.street + " " + self.housenumber.to_s
        end
        unless self.street.nil?
            self.street
        end
    end

    def postal
        unless self.zipcode.nil? || self.city.nil?
            self.zipcode.to_s + " " + self.city
        end
    end
    
    # this will either return all the shops found, or fetch them from Overpass API first
    def self.retrieve(place_id, bounding_box, area_id)
        unless self.where(place_id: place_id).any?
            require 'overpass_api_ruby'

            options={
                :bbox => {
                    :s => bounding_box[0],
                    :w => bounding_box[2],
                    :n => bounding_box[1],
                    :e => bounding_box[3]
                },          
                :timeout => 10,
                :maxsize => 1073741824
            }
    

            overpass = OverpassAPI::QL.new(options)

            query = "
            area(id:#{area_id});
            nwr(area)[shop=supermarket];
            out center;"
    
            shops = overpass.query(query)
        
            current_shop_count = Shop.count
        
            shops[:elements].each do |shop|
                if shop.has_key?(:tags)
                    if shop[:type] == "way"
                        unless shop[:tags][:name].nil? # Guard against empty Sets
                            Shop.find_or_create_by(
                                municipal_name: shop[:display_name],
                                name: shop[:tags][:name],
                                lat: shop[:center][:lat],
                                lon: shop[:center][:lon],
                                street: shop[:tags][:"addr:street"],
                                housenumber: shop[:tags][:"addr:housenumber"],
                                zipcode: shop[:tags][:"addr:postcode"],
                                city: shop[:tags][:"addr:city"],
                                place_id: place_id
                            )
                        end
                    elsif shop[:type] == "node"
                        unless shop[:tags][:name].nil? # Guard against empty Sets
                            Shop.find_or_create_by(
                                municipal_name: shop[:display_name],
                                name: shop[:tags][:name],
                                lat: shop[:lat],
                                lon: shop[:lon],
                                street: shop[:tags][:"addr:street"],
                                housenumber: shop[:tags][:"addr:housenumber"],
                                zipcode: shop[:tags][:"addr:postcode"],
                                city: shop[:tags][:"addr:city"],
                                place_id: place_id
                            )
                        end
                    end
                end
            end
        
            p "Added #{Shop.count - current_shop_count} new shops"
        end
        self.where(place_id: place_id)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.where(place_id: params[:place_id])
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:name, :lat, :lon, :street, :housenumber, :zipcode, :city, :place_id, :municipal_name)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.haml
= form_with(model: shop, local: true) do |form|
  - if shop.errors.any?
    #error_explanation
      %h2
        = pluralize(shop.errors.count, "error")
        prohibited this shop from being saved:
      %ul
        - shop.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :lat
    = form.text_field :lat
  .field
    = form.label :lon
    = form.text_field :lon
  .field
    = form.label :street
    = form.text_field :street
  .field
    = form.label :housenumber
    = form.number_field :housenumber
  .field
    = form.label :zipcode
    = form.number_field :zipcode
  .field
    = form.label :city
    = form.text_field :city
  .field
    = form.label :place_id
    = form.number_field :place_id
  .actions
    = form.submit

app/views/shops/edit.html.haml
%h1 Editing Shop
= render 'form', shop: @shop
= link_to 'Show', @shop
|
= link_to 'Back', shops_path

app/views/shops/index.html.haml
%p#notice= notice
%h1 Shops
%table
  %thead
    %tr
      %th Name
      %th Lat
      %th Lon
      %th Street
      %th Housenumber
      %th Zipcode
      %th City
      %th Place
      %th{:colspan => "3"}
  %tbody
    - @shops.each do |shop|
      %tr
        %td= shop.name
        %td= shop.lat
        %td= shop.lon
        %td= shop.street
        %td= shop.housenumber
        %td= shop.zipcode
        %td= shop.city
        %td= shop.place_id
        %td= link_to 'Show', shop
        %td= link_to 'Edit', edit_shop_path(shop)
        %td= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Shop', new_shop_path

app/views/shops/new.html.haml
%h1 New Shop
= render 'form', shop: @shop
= link_to 'Back', shops_path

app/views/shops/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @shop.name
%p
  %strong Lat:
  = @shop.lat
%p
  %strong Lon:
  = @shop.lon
%p
  %strong Street:
  = @shop.street
%p
  %strong Housenumber:
  = @shop.housenumber
%p
  %strong Zipcode:
  = @shop.zipcode
%p
  %strong City:
  = @shop.city
%p
  %strong Place:
  = @shop.place_id
= link_to 'Edit', edit_shop_path(@shop)
|
= link_to 'Back', shops_path