config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  resources :shops do
    resources :tickets
    resources :census
  end

  #resources :census
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        # get bounding box from input

        unless params.has_key?(:query)
            params[:query] = "Krefeld"
        end

        info = get_info(params[:query])
        @bounding_box = info[0]["boundingbox"]
        @place_id =  info[0]["place_id"]

        osm_id = 666;

        info.each do |record|
            if record["class"] == "boundary" && record["type"] == "administrative" || record["class"] == "place" && record["type"] == "postcode"
                osm_id = record["osm_id"]
                puts "--------------"
                puts osm_id
                break
            end
        end

        area_id = 3600000000 + osm_id

        @shops = Shop.retrieve(@place_id, @bounding_box, area_id).sort_by &:pax
    end

    def get_info(query)
        require 'net/http'
        require 'json'

        url = "https://nominatim.openstreetmap.org/search/#{query}?format=json"
        begin
            uri = URI.parse(url)
          rescue URI::InvalidURIError
            uri = URI.parse(URI.escape(url))
        end
        response = Net::HTTP.get(uri)
        data = JSON.parse(response)
        
        return data
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
= content_for :head do
  :javascript
    const osm_key = "#{Rails.application.credentials.osm[:key]}";
  = javascript_pack_tag 'map', 'data-turbolinks-track': 'reload'

-#.flex.flex-col.h-full.items-center.justify-start.min-h-screen
%main
  #map{"data-place_id": "#{@place_id}", "data-bounds" => "[[#{@bounding_box[0]}, #{@bounding_box[2]}], [#{@bounding_box[1]}, #{@bounding_box[3]}]]"}
    / <iframe src="https://www.openstreetmap.org/#map=14/51.2700/6.5601" frameborder="0"></iframe>
  %form.w-full{:action => ""}
    %section.p-4.flex.flex-col.items-center
      %input.font-bold.p-4.shadow-lg.mt-8{:id => "", :name => "query", :placeholder => "Ort, Stadtteil, PLZ eingeben", value: params[:query], :type => "text"}/
      /
        <section class="my-4 w-full">
        <div class="flex items-center mb-4">
        <img class="w-12 h-12" src="/assets/icons8-überstunden-100.png" alt=""/>
        <h1 class="text-lg">Zeit auswählen</h1>
        </div>
        <div class="flex flex-wrap">
        <h2 class="font-medium py-2 my-1">Ich gehe am</h2>
        <input class="py-2 my-1 mx-2" type="date" name="" id="einkauf_datum">
        <h2 class="font-medium py-2 my-1">um</h2>
        <input class="py-2 my-1 mx-2" type="time" id="einkauf_zeit">
        <h2 class="font-medium py-2 my-1">einkaufen</h2>
        </div>
        </section>
      /
        <section class="my-4 w-full">
        <div class="flex items-center mb-4">
        <img class="w-12 h-12" src="/assets/icons8-geschäft-100.png" alt=""/>
        <h1 class="text-lg">Marktart auswählen</h1>
        </div>
        <ul class="ml-4">
        <li class="p-2 w-full flex items-center">
        <input type="checkbox" name="apotheke" id="apotheke">
        <label class="ml-2 w-full" for="apotheke">Apotheke</label>
        </li>
        <li class="p-2 w-full flex items-center">
        <input type="checkbox" name="supermarkt" id="supermarkt">
        <label class="ml-2 w-full" for="supermarkt">Supermarkt</label>
        </li>
        <li class="p-2 w-full flex items-center">
        <input type="checkbox" name="drogerie" id="drogerie">
        <label class="ml-2 w-full" for="drogerie">Drogerie</label>
        </li>
        <li class="p-2 w-full flex items-center">
        <input type="checkbox" name="bgt_bedarf" id="bgt_bedarf">
        <label class="ml-2 w-full" for="bgt_bedarf">Bau-, Garten- und Tierbedarf</label>
        </li>
        <li class="p-2 w-full flex items-center">
        <input type="checkbox" name="sonstiges" id="sonstiges">
        <label class="ml-2 w-full" for="sonstiges">Sonstiges</label>
        </li>
        </ul>
        </section>
  %section.flex.flex-col.flex-1.w-full.px-8
    / <h1 class="text-center text-gray-500" id="placeholder">Geben Sie einen Ort ein um zu Starten</h1>
    - @shops.each do |shop|
      = link_to new_shop_ticket_path(shop.id) do
        .w-full.border.p-2.bg-white.my-1.rounded{id: shop.id}
          .flex.items-center.mb-2
            .mr-2.rounded-full.h-4.w-4{class: "bg-#{shop.status}-700"}
            %h1.font-medium.text-lg.border-b.w-full= shop.name
          .flex.justify-between.items-end.mb-2
            %h2.font-medium.text-sm
              = shop.address
              %br/
              %span.font-normal= shop.postal
            %code.text-xs= shop.id
          = link_to "Ticket ziehen", new_shop_ticket_path(shop.id), class: "capitalize text-blue-600 underline"