config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  resources :shops do
    resources :tickets
    resources :census
  end

  #resources :census
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :shop

  def is_valid?
    Time.now.between?(self.appointment - 10.minutes, self.appointment + 1.hour)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @census = Censu.new()

    qrcode_info = "https://shopbalancer.herokuapp.com" + url_for(shop_ticket_path(@ticket.shop, @ticket.key))
    require 'rqrcode'
    qrcode = RQRCode::QRCode.new(qrcode_info)

    # NOTE: showing with default options specified explicitly
    @svg = qrcode.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 6,
      standalone: true
    )
  end

  # GET /tickets/new
  def new
    @shop = Shop.find(params[:shop_id])
    @ticket = @shop.tickets.new(appointment: Time.zone.now)
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @shop = Shop.find(params[:shop_id])
    @ticket = @shop.tickets.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        # refetch to get postgres's uuid (key)
        @ticket = Ticket.find(@ticket.id)
        format.html { redirect_to shop_ticket_path(@shop, @ticket.key), notice: 'Ticket erfolgreich erstellt.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.where(key: params[:id]).first
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:shop_id, :appointment)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.haml
%section.p-8
  .flex.items-center.mb-4
    %img.w-12.h-12{:alt => "", :src => "/assets/icons8-überstunden-100.png"}/
    %h1.text-lg Termin erstellen
%main.flex.flex-col.p-8.items-between
  %section
    %section
      = form_with(model: ticket, url: [@shop, @ticket], local: true, class: "flex flex-col") do |form|
        - if ticket.errors.any?
          #error_explanation
            %h2
              = pluralize(ticket.errors.count, "error")
              prohibited this ticket from being saved:
            %ul
              - ticket.errors.full_messages.each do |message|
                %li= message
        %section.my-4.w-full
          .flex.flex-wrap
            %h2.font-medium.py-2.my-1 Ich gehe am
            = form.datetime_local_field :appointment, step: 1, class: "py-2 my-1 mx-2"
            %h2.font-medium.py-2.my-1 einkaufen
        .w-full.border.p-2.bg-white.my-1.rounded
          .flex.items-center.mb-2
            .mr-2.rounded-full.h-4.w-4{class: "bg-#{@shop.status}-700"}
            %h1.font-medium.text-lg.border-b.w-full= @shop.name
          .flex.justify-between.items-end
            %h2.font-medium.text-sm
              = @shop.address
              %br/
              %span.font-normal= @shop.postal
        .mt-16
          %p.mb-2 Achtung : Das Ticket ist ab dem gewählten Termin für 1 Stunde gültig.
          = form.submit "Platz registieren", class: "py-2 px-4 flex-1 text-center bg-blue-400 rounded"

app/views/tickets/edit.html.haml
= render 'form', ticket: @ticket

app/views/tickets/index.html.haml
%p#notice= notice
%h1 Tickets
%table
  %thead
    %tr
      %th Shop
      %th Appointment
      %th{:colspan => "3"}
  %tbody
    - @tickets.each do |ticket|
      %tr
        %td= ticket.shop_id
        %td= ticket.appointment
        %td= link_to 'Show', ticket
        %td= link_to 'Edit', edit_ticket_path(ticket)
        %td= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Ticket', new_ticket_path

app/views/tickets/new.html.haml
= render 'form', ticket: @ticket

app/views/tickets/show.html.haml
%main.flex.flex-col.p-8.items-center
  .my-4.w-full
    .flex.flex-wrap
      %h2.font-medium.py-2.my-1
        Sie haben sich für den
        %strong#einkauf_datum=  @ticket.appointment.strftime("%d.%m.%Y")
        um
        %strong.einkauf_zeit= @ticket.appointment.time.strftime("%H:%M Uhr")
        zum einkaufen eingetragen beim folgenden Supermarkt
  .w-full.my-1.rounded
    .flex.items-center.mb-2
      .mr-2.rounded-full.h-4.w-4{class: "bg-#{@ticket.shop.status}-700"}
      %h1.font-medium.text-lg.border-b.w-full= @ticket.shop.name
    .flex.justify-between.items-end
      %h2.font-medium.text-sm
        = @ticket.shop.address
        %br/
        %span.font-normal= @ticket.shop.postal
  - if @ticket.is_valid?
    .mt-16.mb-4.flex.flex-col.items-center
      = @svg.html_safe
      %h1.my-4.text-center Zeigen Sie diesen QR Code an der Expresskasse vor
      %p
        Ohne die Buchungsbestätigung (QR-Code) ist diese ungültig.
        Bitte speichern Sie diese Seite als Lesezeichen oder machen Sie ein Screenshot.
  - else
    %p
      Das Ticket wird angezeigt sobald es nutzbar ist.
  %br
  = link_to "Zurück", root_path, data: {confirm:"Link gespeichert oder Screenshot gemacht?"}, class: "py-2 px-4 flex-1 text-center bg-blue-400 rounded cursor-pointer"
- if @ticket.is_valid?
  %section.py-4.px-8.bg-white
    %strong.notice= notice
    - unless notice
      %h1.text-lg.font-medium.mb-2.border-b Wie voll war es?
      %p Helfen Sie uns dabei die Sicherheit unserer Mitmenschen zu erhöhen indem Sie angeben wie viele Menschen aktuell vor Ort sind.
      = form_for @census, :url => shop_census_path(@ticket.shop, @census), class: "mt-4" do |form|
        = form.hidden_field :return, value: @ticket.key
        .p-1
          = form.radio_button :sum, 0, :checked => true
          = form.label :sum, 'Leer'
        .p-2
          = form.radio_button :sum, '25'
          = form.label :sum, 'Voll'
        .p-3
          = form.radio_button :sum, '51'
          = form.label :sum, 'Überfüllt'
        = form.submit "Senden", class: "mt-8 flex items-center py-2 px-4 bg-blue-400 justify-center"